# Generated by Django 2.0 on 2018-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks3',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
