# Generated by Django 2.0 on 2018-01-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_auto_20180104_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('my_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.Classes')),
            ],
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='my_class',
            new_name='this_exam',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks1',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks2',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks3',
        ),
        migrations.AddField(
            model_name='marks',
            name='marks_obt',
            field=models.CharField(default='example : 50', max_length=100),
        ),
        migrations.AddField(
            model_name='marks',
            name='roll',
            field=models.CharField(default='example : 2601', max_length=100),
        ),
        migrations.AddField(
            model_name='marks',
            name='student_name',
            field=models.CharField(default='example : ajay verma', max_length=100),
        ),
    ]
