# Generated by Django 2.0 on 2018-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_auto_20180104_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examname',
            name='exam_name',
            field=models.CharField(default='Sessional-1', max_length=100),
        ),
    ]
