# Generated by Django 2.0 on 2018-01-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0005_auto_20180104_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_name',
        ),
    ]
