# Generated by Django 2.0 on 2018-01-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_remove_marks_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obt',
            field=models.CharField(default='ex : 50', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='roll',
            field=models.CharField(default='ex : 2601', max_length=100),
        ),
    ]
