# Generated by Django 2.0 on 2018-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_auto_20180104_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examname',
            name='my_class',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='this_exam',
            new_name='classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='exam_name',
            field=models.CharField(default='Sessional-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='batch',
            field=models.CharField(default='2k15', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='discipline',
            field=models.CharField(default='IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='data structures', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks_obt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='roll',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ExamName',
        ),
    ]
