# Generated by Django 2.0 on 2018-01-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0008_auto_20180104_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.IntegerField(default=60),
        ),
    ]
