# Generated by Django 2.0 on 2018-01-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0009_classes_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
    ]
