# Generated by Django 2.0 on 2018-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0010_remove_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
